# Generated by Django 2.0.3 on 2018-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180411_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(blank=True, max_length=50)),
                ('adult', models.IntegerField(blank=True, max_length=50)),
                ('children', models.IntegerField(blank=True, max_length=50)),
                ('date_of_travel', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
