# Generated by Django 2.0.3 on 2018-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_calculateprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculateprice',
            name='adult',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='calculateprice',
            name='children',
            field=models.IntegerField(blank=True),
        ),
    ]
