# Generated by Django 2.0.3 on 2018-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180411_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculateprice',
            name='date_of_travel',
            field=models.DateField(blank=True, max_length=10),
        ),
    ]
