# Generated by Django 2.0.3 on 2018-04-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0006_auto_20180411_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateprice',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculateprice',
            name='adult',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='calculateprice',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculateprice',
            name='date_of_travel',
            field=models.DateField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='calculateprice',
            name='departure_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
