# Generated by Django 2.0.3 on 2018-04-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20180412_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateprice',
            name='user',
        ),
    ]
