# Generated by Django 2.0.3 on 2018-04-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_remove_calculateprice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
